[theme]
primaryColor="#1DA1F2"  # Twitter blue
backgroundColor="#FFFFFF"  # White background
secondaryBackgroundColor="#E1F5FE"  # Light blue sidebar
textColor="#000000"  # Black text
font="sans serif"
